---
- name: Download and Unzip Maven
  unarchive:
    src: https://dlcdn.apache.org/maven/maven-{{maven_major_version}}/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz
    dest: /opt/
    remote_src: yes
    validate_certs: no
- name: prepare maven env file
  lineinfile:
    dest: /etc/profile.d/maven.sh
    create: yes
    line: "{{ item }}"
    mode: 0755
  loop:
  - 'export M2_HOME=/opt/apache-maven-{{maven_version}}'
  - 'export M2=$M2_HOME/bin'
  - 'export PATH=$PATH:$M2'