---
- name: provision ci server
  hosts: all
  become: yes
  vars_files:
  - vars/vars.yml
  - vars/RedHat-vars.yml
  tasks:
  - name: install Utilities
    yum:
      name:
      - unzip
      - wget
  - name: install Java
    yum:
      name: 
      - "{{java_package}}"
  - name: Install Jenkins
    include_tasks: tasks/jenkins.yml
    tags: ['jenkins']

  - name: Install SonarQube
    include_tasks: tasks/sonar.yml
    tags: ['sonar']

  - name: Install Artifactory
    include_tasks: tasks/artifactory.yml
    tags: ['artifactory']

  - name: Install Docker
    include_tasks: tasks/docker.yml
    tags: ['artifactory']